version: "2"
linters:
  enable:
    - bodyclose
    - dogsled
    - gocritic
    - godox
    - revive
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - whitespace
  settings:
    gocritic:
      disabled-checks:
        - elseif
formatters:
  enable:
    - gofmt
    - goimports
issues:
  exclude-files:
    - asset/asset.go
